export const projects = [
  {
    id: 1,
    title: "Retro Calculator",
    githubUrl: "https://github.com/jakChi/retro-calculator",
    snippet: `https://codepen.io/CamperIO/embed/preview/GRGmQxm?default-tab=result&editable=true&theme-id=dark`,
    className: "calc",
    picSrc: "calc",
    caption: "Retro Style React Calculator",
    link: "",
  },
  {
    id: 2,
    title: "Shopping List",
    githubUrl: "https://github.com/jakChi/Shopping-list",
    snippet: `https://codepen.io/CamperIO/embed/preview/qBQvPVL?default-tab=result&editable=true&theme-id=dark`,
    className: "shop-list",
    picSrc: "shopList",
    caption: "Simple shopping list",
    link: "",
  },
  {
    id: 3,
    title: "Tic-Tac-Toe",
    githubUrl: "https://github.com/jakChi/Tic-Tac-Toe",
    snippet: `https://codepen.io/CamperIO/embed/preview/oNaJVbO?default-tab=result&editable=true&theme-id=dark`,
    className: "tictactoe",
    picSrc: "ticTacToe",
    caption: "Tic-Tac-Toe game",
    link: "",
  },
  {
    id: 4,
    title: "Random Quotes",
    githubUrl: "",
    snippet: `https://codepen.io/CamperIO/embed/preview/ExLaPgZ?default-tab=result&editable=true&theme-id=dark`,
    className: "random-qoute",
    picSrc: "RandomQuote",
    caption: "Random Quote Generator",
    link: "",
  },
  {
    id: 5,
    title: "BMI Calculator",
    githubUrl: "",
    snippet: `https://codepen.io/CamperIO/embed/preview/YzRMVBo?default-tab=result&editable=true&theme-id=dark`,
    className: "bmiCalc",
    picSrc: "bmiCalc",
    caption: "Body Mass Index calculator",
    link: "",
  },
  {
    id: 6,
    title: "Pomodoro Timer",
    githubUrl: "https://github.com/jakChi/Pomodoro-timer",
    snippet: `https://codepen.io/CamperIO/embed/preview/yLwJYRg?default-tab=result&editable=true&theme-id=dark`,
    className: "pomodoro",
    picSrc: "pomodoro",
    caption: "Pomodoro Timer",
    link: "",
  },
  {
    id: 7, 
    title: "Computron",
    githubUrl: "",
    picSrc: "",
    caption: "Amazing messaging app",
    link: "https://computron-8fd9b.web.app"
  }
];
